language: python

env:
  global:
    - CC_TEST_REPORTER_ID=954308f754c8f5a6a4cb65f8473fdcdd017e5fcdd74612cc42899b541d51087e

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install -d

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest --cov-report=xml --cov=blackjack

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
